<h2> Prereq</h2>

<p>
    Make sure you have seen the spring-tiles-bs-jsp-47 project.
</p>

<h2> What is new in this app?</h2>

<h3> Part 8: Using Hibernate and Spring Data JPA</h3>

<ul>
    <li> This requires a bunch of configuration in applicationContext.xml and pom.xml w.r.t.
        some boilerplate copying of stuff!
    </li>
    <li>
        A few errors you'll need to take care of:
        <ol>
            <li>Slf4j error -- the logging mess needs to be taken care of.</li>
            <li>Spring + Maven: The matching wildcard is strict, but no declaration can be found for element
                'jdbc:embedded-database'
            </li>
            <li>java.lang.IllegalArgumentException: No PersistenceProvider specified in EntityManagerFactory
                configuration, and chosen PersistenceUnitInfo does not specify a provider class name either
            </li>
        </ol>
    </li>
    <li> Then you create your first entity, the JPA entity in the entity subpackage!</li>
    <li> Look for this in the log:
        Once this is done, you should see:
        <pre>
            Hibernate: create table User (id bigint generated by default as identity (start with 1),
            primary key (id))
            INFO  2015-03-24 20:38:56,847 [main][SchemaExport.java:405] : HHH000230: Schema export complete
        </pre>
        in the console log
    </li>
</ul>